---
title: "Crypto.com Testnet Node: sagepoint-node"
author: "Roger J Bos, CFA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```





### Install the Crypto.com Testnet on Ubuntu 20.04

Download the binary
```
curl -LOJ https://github.com/crypto-com/chain-main/releases/download/v0.8.0-rc1/chain-main_0.8.0-rc1_Linux_x86_64.tar.gz
tar -zxvf chain-main_0.8.0-rc1_Linux_x86_64.tar.gz
```

Initize the node with a moniker (node name).  Here I am using 'sagepoint-node' as the moniker.
```
chain-maind init sagepoint-node --chain-id testnet-croeseid-2
```

Download the config file from the github site.  It will be saved to a (hidden) directory called .chain-maind in your home director.
```
curl https://raw.githubusercontent.com/crypto-com/testnets/main/testnet-croeseid-2/genesis.json > ~/.chain-maind/config/genesis.json
```

You need to change the `minimum-gas-prices` in the app.toml file.
```
sed -i.bak -E 's#^(minimum-gas-prices[[:space:]]+=[[:space:]]+)""$#\1"0.025basetcro"#' ~/.chain-maind/config/app.toml
```

You need to set the `seeds` in the config.toml file.
```
sed -i.bak -E 's#^(seeds[[:space:]]+=[[:space:]]+).$#\1"b2c6657096aa30c5fafa5bd8ced48ea8dbd2b003@52.76.189.200:26656,ef472367307808b242a0d3f662d802431ed23063@175.41.186.255:26656,d3d2139a61c2a841545e78ff0e0cd03094a5197d@18.136.230.70:26656"# ; s#^(create_empty_blocks_interval[[:space:]]+=[[:space:]]+).$#\1"5s"#' ~/.chain-maind/config/config.toml
```

Add a wallet address.  We will name the address Default, but you can choose any name.  
In Ubuntu 20.04 add the --keyring-backend="test" flag due to known bug.
```
chain-maind keys add Default3 --keyring-backend="test"
```

Pay attention to the string in the `address` field as this is your wallet address where you will receive tokens.  You can use the wallet address in the `from` field for any transactions, but you can also use the wallet `name`, which is easier to remember.  
*Important: Save the seed words so you can restore the wallet if you ever change machines or rebuild your server.  These 24 seed words will never be shown again.*  
If you want to recover an address use this command:
```
chain-maind keys add Default2 --keyring-backend="test" --recover
```

Show wallet address
```
chain-maind keys list --keyring-backend="test"
```

Now you can manually start your node to see if it works.  The `Height` shows the current block it is on.  You may see some errors while it is running, but as long as the `height` is increasing, it is working.
```
chain-maind start
```

Once you are assured it is working, you will probably want to make it run as a service.  I did it by hand, but Crypto.com provides a script you can try:
```
git clone https://github.com/crypto-com/chain-main.git && cd chain-main
./networks/create-service.sh
```

After creating or modifying a service, you need to reload the daemon.
```
sudo systemctl daemon-reload
```

Then you can try starting the service.
```
sudo systemctl start chain-maind
```

Once it is started, you can check the status of it and make sure it didn't fail to start.
```
sudo systemctl status chain-maind
```

If you ever need to stop the service.
```
sudo systemctl stop chain-maind
```

You can view the log of the chain-maind service.
```
journalctl -u chain-maind -f
```

At this point you just need to let your node sync up to the full blockchain, which can take anywhere from a few hours to a few days.
You can see the current height by looking at the log file (above) or by running this command:
```
curl -s http://127.0.0.1:26657/status | jq .result.sync_info.latest_block_height
```

You can compare your node block height to the blockchain height at the [Explorer site](https://chain.crypto.com/explorer/).

Once your node if fully synced up, you can register it as a validator node as follows (note that we are including `--keyring-backend="test"` because we are using Ubuntu 20.04, but if you are using 18.04 you can leave that off):
```
chain-maind tx staking create-validator --keyring-backend="test" \
--amount=5tcro \
--moniker="sagepoint-node" --security-contact="roger.bos@gmail.com" \
--from=Default \
--pubkey=tcrocnclconspub1zcjduepqr37wjtjgqgjshlz5p7z4yzq7t64yslqx07rvcxn832n79n3rzxfqmt7asj \
--chain-id="testnet-croeseid-2" --fees=5000basetcro \
--commission-rate="0.10" --commission-max-rate="0.20" --commission-max-change-rate="0.01" \
--min-self-delegation="1"
```

You will have to have some tokens (TCRO) in order to perform any transactions, including registering as a validator.  If you don't have any TCRO tokens, you can see 10 TCRO each day from the [testnet faucet](https://chain.crypto.com/faucet):

You can check your wallet balance as so (note you can have more than one wallet if you choose):
```
chain-maind query bank balances tcro1tncpcuhh7cedmp9jc6qap4vqm5kxulfapetd6y # Default
```

Here is an example of a send transaction where the tokens are coming from the wallet address defined in the `Default2` keyring and are going to address `tcro1tncpcuhh7cedmp9jc6qap4vqm5kxulfapetd6y`.
```
chain-maind tx bank send Default2 --keyring-backend="test" \
tcro1tncpcuhh7cedmp9jc6qap4vqm5kxulfapetd6y 25000basetcro --chain-id "testnet-croeseid-2" --gas-prices="0.1basetcro"
```

Here is an example of delegating tokens to a validator (probably your own node validator, but you could delegate to someone elses).  When you delegate to someone else's validator node, you are not giving them your tokens and they cannot steal your tokens, but you are trusting there node that it will stay online and collect rewards, which will be shared with you based on how much you delegate.
```
chain-maind tx staking delegate tcrocncl1tncpcuhh7cedmp9jc6qap4vqm5kxulfa5xg5z8 --keyring-backend="test" \
140775basetcro --from="Default2" --chain-id="testnet-croeseid-2" --gas-prices="0.1basetcro" -y
```

To do this, you will need to know the address of your validator.  Mine is `tcrocncl1tncpcuhh7cedmp9jc6qap4vqm5kxulfa5xg5z8`
To find the address of your validator, use this command:
```
chain-maind debug pubkey tcrocnclconspub1zcjduepqr37wjtjgqgjshlz5p7z4yzq7t64yslqx07rvcxn832n79n3rzxfqmt7asj
```

Another way to check the status of your validator node
```
chain-maind status | jq
```

You need to keep your node online and running 24/7 as that is required for the consensus network to operater.  The rewards you get for operating the node are the carrots, and the sticks are slashing and jailing.  If you node is offline for any reason (power outage, internet outage, server crash, etc.) then your power will be slashed (reduced) by a small amount (around 500) and you will be put in jail.  Once you are in jail, you have to wait at least on hour.  Once you notice that you are in jail, make sure your note is fully synced with the blockchain and then issue the following command to unjaill yourself:
```
chain-maind tx slashing unjail --from=Default --chain-id "testnet-croeseid-2" --gas-prices="0.1basetcro"
```

View outstanding rewards for our validator node.  You need to pass in the `tcrocncl1...` validator address.
```
chain-maind q distribution validator-outstanding-rewards tcrocncl1tncpcuhh7cedmp9jc6qap4vqm5kxulfa5xg5z8
```

You can see your validator address as follows:
```
chain-maind keys show Default --keyring-backend="test" --bech val
```

Every few days you may want to withdraw rewards from your validator as they will be not automatically transfered to your wallet.  Once you withdraw them to your wallet, you can delegate them to your validator so that your voting power will eventually increase.
```
chain-maind tx distribution withdraw-all-rewards --keyring-backend="test" --from=Default --chain-id="testnet-croeseid-2" --gas-prices="0.1basetcro"
```

You can unbond funds from a validator using the following command:
```
chain-maind tx staking unbond tcrocncl1wassscvfuu8p87r96xt4etea2wd2lv6juwzxk6 99000000basetcro \
 --keyring-backend="test" --from Default --chain-id "testnet-croeseid-2" --gas-prices="0.1basetcro"
```

There is also a command to see who all has delegated to a validator node.  You can use this to see how much you have delegated to a specific validator so you know how much to unbond, for example.
```
chain-maind query staking delegations-to tcrocncl1tncpcuhh7cedmp9jc6qap4vqm5kxulfa5xg5z8 --output json  | jq
```

If you want to view the entire size of the staking pool:
```
chain-maind query staking pool --output json | jq
```

If you want to see the staking and distribution parameters of your node, you can try the following:
```
chain-maind query staking params --output json | jq
chain-maind query distribution params --output json | jq
```

It might be interesting to see a (json) list of all the validator nodes.
```
chain-maind q staking validators -o json | jq
```

Show Consensus Node Validator & Consensus Node Address
```
chain-maind tendermint show-validator
chain-maind tendermint show-address
```

The keyring contains three addresses.  The account (acc) key is shown by default.
* bech acc is Account address (default if bech is not specified)
* bech val is Validator address
* bech cons is Consensus address
```
chain-maind keys show Default --keyring-backend="test" --bech acc
chain-maind keys show Default --keyring-backend="test" --bech val
chain-maind keys show Default --keyring-backend="test" --bech cons
```
